feat: move asset files to their own directory

diff --git a/dev/bin/package b/dev/bin/package
--- a/dev/bin/package
+++ b/dev/bin/package
@@ -1,26 +1,33 @@
 #!/usr/bin/env bash
+# This script creates a gregstyles.ankiaddon file that can be imported into
+# Anki.
 
 TARGET_PATH="$(readlink -f .)/gregstyles.ankiaddon"
 TMP_DIR=$(mktemp -d)
 
-rm -f "${TARGET_PATH}" || { echo "Failed to remove the existing target file before preparing a new one." >&2; exit 1; }
+rm -f "${TARGET_PATH}" || \
+  { echo "Failed to remove the existing target file before preparing a new one." >&2; exit 1; }
+
+cp -r gregstyles/* "${TMP_DIR}"
+# "asset-files" is meant to named in such a way to prevent collisions with
+# Python packages.
+mkdir "${TMP_DIR}/asset-files" && \
+  cp -r assets/* "${TMP_DIR}/asset-files" || \
+  { echo "Failed to copy assets."; exit 1; }
+
+echo "The temporary directory is ${TMP_DIR}."
+
+pushd $TMP_DIR >/dev/null
 
 # Delete pycache, because Anki forbids it.
 # https://addon-docs.ankiweb.net/sharing.html#:~:text=python%20automatically%20creates%20pycache%20folders%20when%20your%20add-on%20is%20run.%20please%20make%20sure%20you%20delete%20these%20prior%20to%20creating%20the%20zip%20file%2C%20as%20ankiweb%20can%20not%20accept%20zip%20files%20that%20contain%20pycache%20folders.
-find . -name __pycache__ | xargs rm -r || { echo "Failed to remove __pycache__ directories" >&2; exit 1; }
+find . -name __pycache__ | xargs rm -r || \
+  { echo "Failed to remove __pycache__ directories." >&2; exit 1; }
 
-cp gregstyles/*.py "${TMP_DIR}"
-cp gregstyles/manifest.json "${TMP_DIR}"
-mkdir "${TMP_DIR}"/assets
-cp gregstyles/assets/*.py "${TMP_DIR}"/assets
-cp -r assets "${TMP_DIR}"
-
-pushd $TMP_DIR
-zip ${TARGET_PATH} -j \
-  *.py \
-  manifest.json && \
 zip -r ${TARGET_PATH} \
-  assets
-popd
+   *
 
-rm -r "${TMP_DIR}" || { echo "Failed to remove the temporary directory." >&2; exit 1; }
+rm -r "${TMP_DIR}" || {
+  echo "Failed to remove the temporary directory." >&2
+  exit 1
+}
